// Code generated by go-swagger; DO NOT EDIT.

package create_a_visitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"visitor-registry/models"
)

// NewAddVisitorParams creates a new AddVisitorParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddVisitorParams() *AddVisitorParams {
	return &AddVisitorParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddVisitorParamsWithTimeout creates a new AddVisitorParams object
// with the ability to set a timeout on a request.
func NewAddVisitorParamsWithTimeout(timeout time.Duration) *AddVisitorParams {
	return &AddVisitorParams{
		timeout: timeout,
	}
}

// NewAddVisitorParamsWithContext creates a new AddVisitorParams object
// with the ability to set a context for a request.
func NewAddVisitorParamsWithContext(ctx context.Context) *AddVisitorParams {
	return &AddVisitorParams{
		Context: ctx,
	}
}

// NewAddVisitorParamsWithHTTPClient creates a new AddVisitorParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddVisitorParamsWithHTTPClient(client *http.Client) *AddVisitorParams {
	return &AddVisitorParams{
		HTTPClient: client,
	}
}

/* AddVisitorParams contains all the parameters to send to the API endpoint
   for the add visitor operation.

   Typically these are written to a http.Request.
*/
type AddVisitorParams struct {

	/* Body.

	   Visitor data structure for registering one
	*/
	Body *models.Visitor

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add visitor params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddVisitorParams) WithDefaults() *AddVisitorParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add visitor params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddVisitorParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add visitor params
func (o *AddVisitorParams) WithTimeout(timeout time.Duration) *AddVisitorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add visitor params
func (o *AddVisitorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add visitor params
func (o *AddVisitorParams) WithContext(ctx context.Context) *AddVisitorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add visitor params
func (o *AddVisitorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add visitor params
func (o *AddVisitorParams) WithHTTPClient(client *http.Client) *AddVisitorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add visitor params
func (o *AddVisitorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add visitor params
func (o *AddVisitorParams) WithBody(body *models.Visitor) *AddVisitorParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add visitor params
func (o *AddVisitorParams) SetBody(body *models.Visitor) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddVisitorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
