// Code generated by go-swagger; DO NOT EDIT.

package get_a_visitor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"visitor-registry/models"
)

// GetVisitorReader is a Reader for the GetVisitor structure.
type GetVisitorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVisitorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVisitorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetVisitorInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetVisitorOK creates a GetVisitorOK with default headers values
func NewGetVisitorOK() *GetVisitorOK {
	return &GetVisitorOK{}
}

/* GetVisitorOK describes a response with status code 200, with default header values.

A list of products
*/
type GetVisitorOK struct {
	Payload []*models.Visitor
}

func (o *GetVisitorOK) Error() string {
	return fmt.Sprintf("[GET /visitor][%d] getVisitorOK  %+v", 200, o.Payload)
}
func (o *GetVisitorOK) GetPayload() []*models.Visitor {
	return o.Payload
}

func (o *GetVisitorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVisitorInternalServerError creates a GetVisitorInternalServerError with default headers values
func NewGetVisitorInternalServerError() *GetVisitorInternalServerError {
	return &GetVisitorInternalServerError{}
}

/* GetVisitorInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type GetVisitorInternalServerError struct {
	Payload *models.GenericError
}

func (o *GetVisitorInternalServerError) Error() string {
	return fmt.Sprintf("[GET /visitor][%d] getVisitorInternalServerError  %+v", 500, o.Payload)
}
func (o *GetVisitorInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *GetVisitorInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
